export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const TOKEN_INFOS = "TOKEN_INFOS";
export const GET_ACCOUNTS = "GET_ACCOUNTS";
export const LOGOUT = "LOGOUT";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE";