swagger: '2.0'
info:
  title: Bank Argent API Documentation
  description: API endpoints for managing bank transactions.
  version: '1.0.0'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/{id}/transactions:
    get:
      summary: Get user month's transactions
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: A list of transactions of the month.
          schema:
            type: array
            items:
              type: object
              properties:
                id: { type: string }
                date: { type: string, format: date-time }
                description: { type: string }
                amount: { type: number }
                balance: { type: number }
        '401': { description: Unauthorized }
        '404': { description: Not Found }
        '500': { description: Internal Server Error }
      security:
            - Bearer: []

  /user/{id}/transactions/{transactionId}:
    get:
      summary: Get transaction details
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - name: transactionId
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Transaction details.
          schema:
            type: object
            properties:
              id: { type: string }
              date: { type: string, format: date-time }
              description: { type: string }
              amount: { type: number }
              balance: { type: number }
              transactionType: { type: string }
              category: { type: string }
              notes: { type: string }
              accountNumber: { type: string }
        '401': { description: Unauthorized }
        '404': { description: Not Found }
        '500': { description: Internal Server Error }
      security:
            - Bearer: []

    put:
      summary: Update transaction
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - name: transactionId
          in: path
          required: true
          type: string
        - in: body
          name: transactionUpdate
          schema:
            type: object
            properties:
              transactionType: { type: string }
              category: { type: string }
              notes: { type: string }
      responses:
        '200': { description: Transaction updated }
        '400': { description: Bad Request }
        '401': { description: Unauthorized }
        '404': { description: Not Found }
        '500': { description: Internal Server Error }
      security:
            - Bearer: []

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    description: 'JWT Authorization header with the Bearer scheme'
