swagger: '2.0'
info:
  title: Bank Argent API Documentation
  description: API endpoints for managing bank transactions.
  version: '1.0.0'
host: localhost:3001
basePath: /api/v1
schemes:
  - http

paths:
  /user/{id}/accounts:
    get:
      security:
        - Bearer: []
      tags:
        - accounts module
      summary: Get user's accounts
      parameters:
        - in: header
          name: Authorization
          description: JWT token
          required: true
          type: string
        - name: id
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: A list of user accounts.
          schema:
            type: array
            items:
              type: object
              properties:
                accountId: { type: string }
                accountType: { type: string }
                balance: { type: number }
        '401': { description: Unauthorized }
        '404': { description: Not Found }
        '500': { description: Internal Server Error }

  /user/{id}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - transactions module
      summary: Get user month's transactions
      parameters:
        - in: header
          name: Authorization
          description: JWT token
          required: true
          type: string
        - name: id
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: A list of transactions of the month.
          schema:
            type: array
            items:
              type: object
              properties:
                accountType: { type: string }
                id: { type: string }
                date: { type: string, format: date-time }
                description: { type: string }
                amount: { type: number }
                balance: { type: number }
        '401': { description: Unauthorized }
        '404': { description: Not Found }
        '500': { description: Internal Server Error }

  /user/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - transactions's detail module
      summary: Get transaction details
      parameters:
        - in: header
          name: Authorization
          description: JWT token
          required: true
          type: string
        - name: transactionId
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Transaction details
          schema:
            type: object
            properties:
              userId : { type: string }
              id: { type: string }
              date: { type: string, format: date-time }
              description: { type: string }
              amount: { type: number }
              balance: { type: number }
              transactionType: { type: string }
              category: { type: string }
              notes: { type: string }
              accountNumber: { type: string }
              accountType: { type: string }
        '401': { description: Unauthorized }
        '404': { description: Not Found }
        '500': { description: Internal Server Error }

    put:
      security:
        - Bearer: []
      tags: 
        - update transaction's detail
      summary: Update transaction
      parameters:
        - in: header
          name: Authorization
          description: JWT token
          required: true
          type: string
        - name: transactionId
          in: path
          required: true
          type: string
        - in: body
          name: transactionUpdate
          schema:
            type: object
            properties:
              transactionType: { type: string }
              category: { type: string }
              notes: { type: string }
      produces:
        - application/json
      responses:
        '200': { description: Transaction updated }
        '400': { description: Bad Request }
        '401': { description: Unauthorized }
        '404': { description: Not Found }
        '500': { description: Internal Server Error }

  /user/transactions/{transactionId}/note:
    delete:
      security:
        - Bearer: []
      tags:
        - transactions's detail module
      summary: Delete a note from a transaction
      parameters:
        - in: header
          name: Authorization
          description: JWT token
          required: true
          type: string
        - name: transactionId
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200': { description: Note deleted from the transaction }
        '400': { description: Bad Request }
        '401': { description: Unauthorized }
        '404': { description: Not Found }
        '500': { description: Internal Server Error }

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    description: 'JWT Authorization header with the Bearer scheme'
